In [2]:
import pandas as pd

cart_log = pd.read_csv('../input/cart_log.csv')
coupon_target_jan = pd.read_csv('../input/coupon_target_jan.csv')
coupon = pd.read_csv('../input/coupon.csv')
price = pd.read_csv('../input/price.csv')
product_master = pd.read_csv('../input/product_master.csv')
session = pd.read_csv('../input/session.csv')
test_session = pd.read_csv('../input/test_session.csv')

/home/yoshikawa/.pyenv/versions/3.7.10/envs/kaggle/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3170: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
cart_log.head(40)

,session_id,duration,action_name,action_detail,item_name,item_detail,item_detail_add_1,item_detail_add_2,coupon_is_activated,JAN,n_items,created_at__date,created_at__hour
0,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,26,PIN入力,PIN入力,キー,****,NaN,NaN,0,NaN,0,2021-12-04,11
1,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,550,買物,商品追加,商品,2533871000000,みかんM 大箱,1.0,0,2.533871e+12,1,2021-12-04,11
2,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,622,買物,商品追加,商品,2533871000000,みかんM 大箱,1.0,0,2.533871e+12,1,2021-12-04,11
3,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,698,買物,商品追加,商品,4972807218857,大盛__白糸こんにゃく５０,1.0,0,4.972807e+12,1,2021-12-04,11
4,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,701,買物,商品追加,商品,4972807218857,大盛__白糸こんにゃく５０,1.0,0,4.972807e+12,1,2021-12-04,11
5,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,746,買物,商品追加,商品,4974612101027,ベビーシュークリーム,1.0,0,4.974612e+12,1,2021-12-04,11
6,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,853,買物,商品追加,商品,4903301263944,システマハブラシ 超コン,1.0,0,4.903301e+12,1,2021-12-04,11
7,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,861,買物,商品追加,商品,4971666488623,アーモンド効果_砂糖不使用,1.0,0,4.971666e+12,1,2021-12-04,11
8,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,862,買物,商品追加,商品,4971666488623,アーモンド効果_砂糖不使用,1.0,0,4.971666e+12,1,2021-12-04,11
9,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,981,買物,商品追加,商品,4903110063278,薄皮つぶあんぱん,1.0,0,4.903110e+12,1,2021-12-04,11
10,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,1077,レジ袋,枚数入力,商品,4522646330991,レジ袋,0.0,0,4.522646e+12,0,2021-12-04,11
11,00011e97d485ffb7f78662972da6032d4103b1628d541f...,9,PIN入力,PIN入力,キー,****,NaN,NaN,0,NaN,0,2021-11-18,19
12,00011e97d485ffb7f78662972da6032d4103b1628d541f...,49,買物,商品追加,商品,4902888219368,ダース ミルク,1.0,0,4.902888e+12,1,2021-11-18,19
13,00011e97d485ffb7f78662972da6032d4103b1628d541f...,51,買物,商品追加,商品,4902888219368,ダース ミルク,1.0,0,4.902888e+12,1,2021-11-18,19
14,00011e97d485ffb7f78662972da6032d4103b1628d541f...,81,買物,商品追加,商品,4580030180010,パイン２００ｇ,1.0,0,4.580030e+12,1,2021-11-18,19
15,00011e97d485ffb7f78662972da6032d4103b1628d541f...,154,買物,商品追加,商品,4582273300477,漢江物産 鶴橋直送しぼり,1.0,0,4.582273e+12,1,2021-11-18,19
16,00011e97d485ffb7f78662972da6032d4103b1628d541f...,158,買物,商品追加,商品,4582273300477,漢江物産 鶴橋直送しぼり,1.0,0,4.582273e+12,1,2021-11-18,19
17,00011e97d485ffb7f78662972da6032d4103b1628d541f...,170,買物,商品追加,商品,4582273300484,直送鶴橋 胡瓜キムチ,1.0,0,4.582273e+12,1,2021-11-18,19
18,00011e97d485ffb7f78662972da6032d4103b1628d541f...,264,買物,商品追加,商品,4580019240506,スタミナ白菜,1.0,0,4.580019e+12,1,2021-11-18,19
19,00011e97d485ffb7f78662972da6032d4103b1628d541f...,468,買物,商品追加,商品,4901777328723,伊右衛門プラスコレステロ,1.0,0,4.901777e+12,1,2021-11-18,19
20,00011e97d485ffb7f78662972da6032d4103b1628d541f...,485,買物,商品追加,商品,2545566000000,チーズタッカルビピザ（チ,1.0,0,2.545566e+12,1,2021-11-18,19
21,00011e97d485ffb7f78662972da6032d4103b1628d541f...,524,買物,商品追加,商品,4560294953124,キャラメルポップコーン,1.0,0,4.560295e+12,1,2021-11-18,19
22,00011e97d485ffb7f78662972da6032d4103b1628d541f...,614,買物,商品追加,商品,4902111727103,モッズ・ヘア_グラマラスメ,1.0,0,4.902112e+12,1,2021-11-18,19
23,00011e97d485ffb7f78662972da6032d4103b1628d541f...,618,買物,商品追加,商品,4902111727103,モッズ・ヘア_グラマラスメ,1.0,0,4.902112e+12,1,2021-11-18,19
24,00011e97d485ffb7f78662972da6032d4103b1628d541f...,981,レジ袋,枚数入力,商品,4522646330991,レジ袋,0.0,0,4.522646e+12,0,2021-11-18,19
25,00011e97d485ffb7f78662972da6032d4103b1628d541f...,1016,バーコードがない商品,商品選択,商品,2532153000999,トマト１玉,NaN,0,2.532153e+12,0,2021-11-18,19
26,00011e97d485ffb7f78662972da6032d4103b1628d541f...,1017,買物,商品追加,商品,2532153000000,トマト１玉,1.0,0,2.532153e+12,1,2021-11-18,19
27,00011e97d485ffb7f78662972da6032d4103b1628d541f...,1021,買物,商品追加,商品,4954356299198,ＴＲちゃんぽん,1.0,0,4.954356e+12,1,2021-11-18,19
28,00011e97d485ffb7f78662972da6032d4103b1628d541f...,1031,レジ袋,枚数入力,商品,4522646330991,レジ袋,0.0,0,4.522646e+12,0,2021-11-18,19
29,000280d2156d179a597167b269a69e5af556725eeaabae...,8,PIN入力,PIN入力,キー,****,NaN,NaN,0,NaN,0,2022-01-25,13
30,000280d2156d179a597167b269a69e5af556725eeaabae...,83,バーコードがない商品,商品選択,商品,2532309000996,キャベツ１玉,NaN,0,2.532309e+12,0,2022-01-25,13
31,000280d2156d179a597167b269a69e5af556725eeaabae...,85,バーコードがない商品,数量入力,商品,2532309000996,キャベツ１玉,1.0,0,2.532309e+12,0,2022-01-25,13
32,000280d2156d179a597167b269a69e5af556725eeaabae...,85,買物,商品追加,商品,2532309000000,キャベツ１玉,1.0,0,2.532309e+12,1,2022-01-25,13
33,000280d2156d179a597167b269a69e5af556725eeaabae...,119,買物,商品追加,商品,4935113309657,みかん Ｍ,1.0,0,4.935113e+12,1,2022-01-25,13
34,000280d2156d179a597167b269a69e5af556725eeaabae...,155,買物,商品追加,商品,2532658000000,スナップえんどう国産,1.0,0,2.532658e+12,1,2022-01-25,13
35,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,9,PIN入力,PIN入力,キー,****,NaN,NaN,0,NaN,0,2021-12-20,17
36,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,256,買物,商品追加,商品,4901070130115,お部屋の消臭力ＰＡＳｔｉ,1.0,0,4.901070e+12,1,2021-12-20,17
37,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,330,買物,商品追加,商品,4580025410399,Ｐｕｒｕｎｔモイストリッ,1.0,0,4.580025e+12,1,2021-12-20,17
38,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,343,買物,商品追加,商品,4582521682256,YOLU２連サシェ,1.0,0,4.582522e+12,1,2021-12-20,17
39,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,378,買物,商品追加,商品,4952195624669,ルベル イオ エッセンス,1.0,0,4.952196e+12,1,2021-12-20,17

In [4]:
cart_log.describe()

,duration,coupon_is_activated,JAN,n_items,created_at__hour
count,1.802022e+06,1.802022e+06,1.608060e+06,1.802022e+06,1.802022e+06
mean,7.431467e+02,8.715765e-03,4.220833e+12,7.550502e-01,1.443414e+01
std,7.032270e+02,9.295055e-02,1.209011e+12,7.644845e-01,3.870704e+00
min,0.000000e+00,0.000000e+00,2.723220e+06,-1.990000e+02,0.000000e+00
25%,1.900000e+02,0.000000e+00,4.514603e+12,1.000000e+00,1.200000e+01
50%,5.540000e+02,0.000000e+00,4.901331e+12,1.000000e+00,1.500000e+01
75%,1.079000e+03,0.000000e+00,4.902930e+12,1.000000e+00,1.700000e+01
max,5.395000e+03,1.000000e+00,9.555702e+12,9.900000e+01,2.300000e+01

In [5]:
session.head(20)

,session_id,registor_number,user_id,sex,age,distance_to_the_store,start_at__date,start_at__hour
0,00003ee1b7f34620ae81dba533c6d5a544513004fe5688...,1097,5e9b4221190f5cc4d678381fc2ba592426b6ee2e6d4eb2...,女性,60~64,2,2021-12-04,11
1,00011e97d485ffb7f78662972da6032d4103b1628d541f...,1045,ce397b59fd9633c11a8b659d8ba49ab024cbe9186c2d30...,女性,55~59,4,2021-11-18,19
2,000280d2156d179a597167b269a69e5af556725eeaabae...,1016,8da8267f34ec7ee3f3b800b089b7e27c16fe8cf5a7e36b...,女性,35~39,17,2022-01-25,13
3,0002a4a49d2230456ce57f9709b7c97e1ee324906f4ed8...,1047,b943a6cfb8e1a2b7c97aa9486d1ca7a8ab16ce40a39a72...,女性,30~34,18,2021-12-20,17
4,000383cb2018d041d4976a0e26d2dc0b73918abd5a30c9...,1081,35d09cb3d4bf8998191ea6b4ed8b8a2d0ff089b0eadc96...,女性,25~29,2,2021-11-11,8
5,0003e5680ce8e8dd13df8f4d1f1acd20b316282ef9530a...,1126,008dc712004b7bb8fe8c26d81ff192ecc35f654e639c3b...,女性,30~34,2,2021-12-24,20
6,00042d04c4760f6a22aa21bc7ac475b269ae0f3b90674e...,1104,ff49efdd19a69f49eed0e36d5f6dafdbf0c3546c6001d0...,女性,55~59,1,2021-11-09,15
7,00044b68f565ef63a2fbe7d7d3b97855b6708ef7b6f522...,1045,7111f2d0f8e1b81f0641578b66511955c936bdecf87763...,女性,50~54,不明,2021-11-10,14
8,0005318278c96d21679863f94df45fabc8ff6a64922c4b...,1078,4a9e54c9c513d32de062d9317f2b8d0e4fb0d444cee351...,男性,70~74,3,2021-12-16,12
9,00055a0719ae8afefe0a785d4099a98da414b72345b2d9...,1051,79f9d3fa4006cb284677e95194543a3ccfe3db55cf5294...,女性,65~69,3,2022-01-12,21
10,00069c8b8624c0e4a8eb49af73076d8957ebb0a66cd424...,1070,520859ce97e033aaa8d97ea1044d4208d2789294e2ca3a...,女性,70~74,3,2021-12-10,17
11,0006ae3f8ed3909c19b4cb8fa1cc68b8beb12307938d50...,1143,ace365d01e96186a695cc667eb6e954472d9132c473995...,女性,45~49,4,2021-11-18,18
12,0006b0a4b9758efc3273b7e7780d08c7079967d0648771...,1060,30fbe9832a49e7646e945adc746d13adcf89a476558b6f...,不明,不明,不明,2021-12-21,17
13,0006b38d31026cb723dd14ab317835c6d23ff17b14d98d...,1057,4e5f505df4ae3ce9b4c295a9e185f81564e9868b95276b...,男性,70~74,3,2021-12-31,11
14,0008030d60a542f1b8a1f6d01bc97d9c49147bf8de0e61...,1060,3462ed32ffc380b1e33c1ee78b3e37cbaaeea94cf47b4f...,女性,45~49,1,2022-01-06,17
15,00082c3c0a9b17c0c7d1d726857e08f41fa2b03b4f209d...,1134,13730aa44a8409392aa49de1e5bab05ff8e4291971e3f3...,女性,60~64,2,2021-11-16,14
16,000872d86bf8476af853be7b4afd564bf8200ea3cd27fa...,1124,0bc21086d17fb027abd7f16523c5f5df70cdc2826a5530...,男性,60~64,3,2021-11-21,16
17,0009065eec287b1cedc44425b2b53c82aba347bf9966be...,1117,8b2894cef5e1de80f0b13cc33655f9bf5d5442da3d3aac...,女性,65~69,5,2022-01-16,13
18,0009d6a7cbae2ef371ada6b9a3f9dd17670bf82022a23a...,1014,dc3c60e9666223f918f2dfdb5289592cc0b84860f19d2a...,男性,15~19,1,2021-12-09,21
19,000a05e0d7f5b4fcb1d07e01704382df523bb8efa08f8e...,1093,3d97b86a6eea8d844077ab368f11a84ad2810d4b5ecfa7...,女性,70~74,11,2021-12-13,10

In [6]:
session.shape

(109161, 8)

In [7]:
test_session.head()

                                          session_id
0  000280d2156d179a597167b269a69e5af556725eeaabae...
1  00055a0719ae8afefe0a785d4099a98da414b72345b2d9...
2  0009065eec287b1cedc44425b2b53c82aba347bf9966be...
3  000efa1223901c67e9abc8030b55218240174b6c793289...
4  001019dafd085898d4bcd7631468af2b3ccb6120b71bac...

In [8]:
price.head(20)

          date       JAN  avg_price  min_price  max_price
0   2021-11-01   2782621      520.0        520        520
1   2021-11-01   2853422      540.0        540        540
2   2021-11-01  45019517       99.0         99         99
3   2021-11-01  45044182       99.0         99         99
4   2021-11-01  45048296      399.0        399        399
5   2021-11-01  45070266      179.0        179        179
6   2021-11-01  45089008      890.0        890        890
7   2021-11-01  45091520      135.0        135        135
8   2021-11-01  45091568      130.0        130        130
9   2021-11-01  45096716      135.0        135        135
10  2021-11-01  45097010       59.0         59         59
11  2021-11-01  45104916      129.0        129        129
12  2021-11-01  45113642      580.0        580        580
13  2021-11-01  45113659      420.0        420        420
14  2021-11-01  45114908       99.0         99         99
15  2021-11-01  45116568       79.0         79         79
16  2021-11-01  45121647      199.0        199        199
17  2021-11-01  45121654      249.0        249        249
18  2021-11-01  45131646      549.0        549        549
19  2021-11-01  45131677      549.0        549        549

In [9]:
coupon_target_jan.head()

   coupon_id            JAN
0      50084  4901313937853
1      50085  4903901179652
2      50086  4901326036376
3      50087  4901326110724
4      50088  4902450465209

In [10]:
coupon.head()

,coupon_id,name,display_category_name,point_expired_date,point_value,point_type
0,50084,つまみ種 亀田製菓,お菓子,2021-11-07,10,2
1,50085,コメダ珈琲店キャンディー,お菓子,2021-11-07,5,2
2,50086,女王のミルク 春日井製菓,お菓子,2021-11-07,5,2
3,50087,ラムネいろいろ 春日井製菓,お菓子,2021-11-07,5,2
4,50088,ぼんち 海鮮揚煎おじゃこ揚げせん,お菓子,2021-11-07,5,2

In [11]:
product_master.head(30)

,JAN,name,department,category,sub_category,segment,sub_segment,target
0,1,テナント商品1,未登録等,未登録等その他,未登録等その他,その他,その他,0
1,2,テナント商品2,未登録等,未登録等その他,未登録等その他,その他,その他,0
2,3,テナント商品3,未登録等,未登録等その他,未登録等その他,その他,その他,0
3,4,テナント商品4,未登録等,未登録等その他,未登録等その他,その他,その他,0
4,5,テナント商品5,未登録等,未登録等その他,未登録等その他,その他,その他,0
5,6,テナント商品6,未登録等,未登録等その他,未登録等その他,その他,その他,0
6,7,テナント商品7,未登録等,未登録等その他,未登録等その他,その他,その他,0
7,8,テナント商品8,未登録等,未登録等その他,未登録等その他,その他,その他,0
8,9,寿司(惣菜)_部門,寿司(惣菜),原料・包材（寿司）,包材（寿司）,包材（寿司）,設定なし,0
9,10,テナント商品10,未登録等,未登録等その他,未登録等その他,その他,その他,0
10,11,テナント商品11,未登録等,未登録等その他,未登録等その他,その他,その他,0
11,12,テナント商品12,未登録等,未登録等その他,未登録等その他,その他,その他,0
12,13,テナント商品13,未登録等,未登録等その他,未登録等その他,その他,その他,0
13,14,テナント商品14,未登録等,未登録等その他,未登録等その他,その他,その他,0
14,15,テナント商品15,未登録等,未登録等その他,未登録等その他,その他,その他,0
15,16,テナント商品16,未登録等,未登録等その他,未登録等その他,その他,その他,0
16,17,テナント商品17,未登録等,未登録等その他,未登録等その他,その他,その他,0
17,18,テナント商品18,未登録等,未登録等その他,未登録等その他,その他,その他,0
18,19,テナント商品19,未登録等,未登録等その他,未登録等その他,その他,その他,0
19,20,テナント商品20,未登録等,未登録等その他,未登録等その他,その他,その他,0
20,21,テナント商品21,未登録等,未登録等その他,未登録等その他,その他,その他,0
21,22,テナント商品22,未登録等,未登録等その他,未登録等その他,その他,その他,0
22,23,テナント商品23,未登録等,未登録等その他,未登録等その他,その他,その他,0
23,24,テナント商品24,未登録等,未登録等その他,未登録等その他,その他,その他,0
24,25,テナント商品25,未登録等,未登録等その他,未登録等その他,その他,その他,0
25,26,テナント商品26,未登録等,未登録等その他,未登録等その他,その他,その他,0
26,27,テナント商品27,未登録等,未登録等その他,未登録等その他,その他,その他,0
27,28,テナント商品28,未登録等,未登録等その他,未登録等その他,その他,その他,0
28,29,牛肉 部門,加工,原材料,原材料,原材料,原材料,0
29,30,テナント商品30,未登録等,未登録等その他,未登録等その他,その他,その他,0

In [12]:
product_master[product_master.category=='チーズ']

,JAN,name,department,category,sub_category,segment,sub_segment,target
450,1926200,ムーンダラークリームチーズ,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
1278,30045002,ﾐﾆﾊﾟｳﾞｪﾀﾞﾌｨｰﾉﾜ,乳製品,チーズ,ナチュラルチーズ,ハード・セミハード,ハード・セミハード,1
2262,45080500,ｸﾘｰﾑﾁｰｽﾞ&ｶﾞｰﾘｯｸ,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2263,45080555,ｸﾘｰﾑﾁｰｽﾞ&Bﾍﾟｯﾊﾟｰ,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2825,45114335,ミルクの里出雲クリームチーズ,乳製品,チーズ,ナチュラルチーズ,ハード・セミハード,ハード・セミハード,1
...,...,...,...,...,...,...,...,...
2073992,9316160000752,ジャイクロクリームチーズ トリプルベリー,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2074028,9329427073055,クリームチーズブロック,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2074081,9415007000389,ﾆｭｰｼﾞｰﾗﾝﾄﾞｸﾘｰﾑﾁｰｽﾞ,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2074082,9415007009542,ﾆｭｰｼﾞｰﾗﾝﾄﾞｸﾘｰﾑ_1kg,乳製品,チーズ,ナチュラルチーズ,クリームチーズ,クリームチーズ,1
2074612,9999999990154,乳製品,乳製品,チーズ,ナチュラルチーズ,ハード・セミハード,ハード・セミハード,1

In [13]:
test_session.shape

(25823, 1)

In [14]:
submit = pd.read_csv('../input/atmaCup13_sample_submission.csv')
submit.shape

(25823, 1)